branches:
  except:
    - gh-pages
language: perl
perl:
  - "5.16"
before_install:
  - sudo apt-get install libhunspell-1.3-0 libhunspell-dev
  - curl https://raw.githubusercontent.com/JJ/Test-Text/master/data/Spanish.aff -o Spanish.aff
  - curl https://raw.githubusercontent.com/SublimeText/Dictionaries/master/Spanish.dic -o Spanish.dic
install: cpanm Test::Text TAP::Harness
script: perl -MTAP::Harness -e 'my $harness = TAP::Harness->new( { verbosity => 0} ); $harness->runtests( "t/just_check.t" );'

